from aiogram.types import InlineKeyboardMarkup,InlineKeyboardButton

menu = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📄 Подать заявление',callback_data='menu_1')
btn2 = InlineKeyboardButton(text='⚖️ Права клиента',callback_data='menu_2')
btn3 = InlineKeyboardButton(text='🏛 Гос. помощь по программе',callback_data='menu_3')
btn4 = InlineKeyboardButton(text='👨‍💼 Поддержка',callback_data='menu_4')
btn5 = InlineKeyboardButton(text='❓ FAQ',callback_data='menu_5')
menu.insert(btn1)
menu.insert(btn2)
menu.insert(btn3)
menu.insert(btn4)
menu.insert(btn5)

menu_2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📥 На возврат средств',callback_data='menu_2_1')
btn2 = InlineKeyboardButton(text='📄 На обжалование решения',callback_data='menu_2_2')
btn3 = InlineKeyboardButton(text='💬 На консультирование',callback_data='menu_2_3')
btn4 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu')
menu_2.insert(btn1)
menu_2.insert(btn2)
menu_2.insert(btn3)
menu_2.insert(btn4)

menu_3 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🔎 Критерии участия',callback_data='menu_3_1')
btn2 = InlineKeyboardButton(text='📑 Список документов',callback_data='menu_3_2')
btn3 = InlineKeyboardButton(text='❓ Часто задаваемые вопросы',callback_data='menu_3_3')
btn4 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu')
menu_3.insert(btn1)
menu_3.insert(btn2)
menu_3.insert(btn3)
menu_3.insert(btn4)

back = InlineKeyboardMarkup(row_width=1)
btn2 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu')
back.insert(btn1)

cancel = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Отмена',callback_data='cancel')
cancel.insert(btn1)